### ISSUE TITLE
Password in stored in plaintext during automatic operation

### ISSUE THREAD

**Issue by bradleymackey** [bradleymackey/turbo-boost-disable#1]
This is a big potential security vulnerability if other users use the computer or if full disk encryption is not enabled. Any suggestions on how to get root in a new shell without requiring the password each time?

**Comment by TimNN** [comment]
At least on Linux, the „sudoers“ file can be set up so that specific commands, with specific arguments, are allowed without requiring a password: https://askubuntu.com/a/159009

**Comment by bradleymackey** [comment]
README resolves issues. Apologies for this hiccup folks.
