### ISSUE TITLE
Sudo configuration not safe

### ISSUE THREAD

**Issue by akx** [bradleymackey/turbo-boost-disable#2]
With the changes in https://github.com/bradleymackey/turbo-boost-disable/commit/2a9cae1f245fcd3afd6e72a09347d8f5136db9d4 , the configuration is not exactly safe either.

Something malicious running as `myusername` can modify `/Users/myusername/turbo-boost-disable/{load,unload}.sh` and then execute `sudo /Users/myusername/turbo-boost-disable/load.sh` to run their code as root.

**Comment by bradleymackey** [comment]
Does 727d857784a02d05422547db9de69fbffb5c2e5d fix this?

**Comment by TimNN** [comment]
I think you‘ll get better security by adding the „kextunload“ commands to „sudoers“ and having the „chown“ as a manual setup step.

**Comment by bradleymackey** [comment]
I don't want an arbitrary `kextunload` commands to be allowed to run though. Is it not better to only 'whitelist' this one specific script and make that read-execute-only?

**Comment by TimNN** [comment]
You can whitelist the commands to load / unload this one specific extension.

**Comment by bradleymackey** [comment]
I'll keep it as it is for now. It addresses the main issue but I'll be happy to merge any better PRs.

**Comment by akx** [comment]
@bradleymackey No, 727d857 is only a hurdle. An attacker will just need to chown to allow writing before doing their nefarious deeds, i.e.

```
chown u+w /Users/myusername/turbo-boost-disable/load.sh
echo 'evil.sh' >> /Users/myusername/turbo-boost-disable/load.sh
```

The more correct solution would be that the scripts are owned by root, not writable and [have setuid](https://en.wikipedia.org/wiki/Setuid#When_set_on_an_executable_file) on them, so you're effectively escalated to root when executing them. (`sudo` itself is setuid, btw.) Naturally you'd have to be careful to avoid user input being executed or misused in a setuid script.

**Comment by bradleymackey** [comment]
I think it's solved now. `root` owns the scripts, then denies writes to other users:
```sh
$ sudo chown root:wheel *.sh
$ sudo chmod 4755 *.sh
```
Thanks for the help by the way.
